### PR TITLE
MNT: Re-rendered with conda-build 3.18.11 and conda-smithy 3.7.4

### PR DESCRIPTION
**Pull request by st3107**
Hi @mrakitin I did the edits according to your comments. Ready for review.

### CODE REVIEW

**Comment by st3107** [comment]
Build failed. Debugging ... Oh I use the wrong env variable name.

**Comment by st3107** [comment]
It seems that I cannot push the edits because

```
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/v0.7.4_3.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:nsls-ii-forge/shed-feedstock.git
 ! [remote rejected] v0.7.4_3 -> v0.7.4_3 (protected branch hook declined)
error: failed to push some refs to 'git@github.com:nsls-ii-forge/shed-feedstock.git'
```

Maybe I should for this feedstock and create branchs in my fork and submit a PR. This PR is closed.

**Comment by mrakitin** [comment]
@st3107, strange. I set some branch protection rules to require commits to pass the CI and to require at least one review for all projects labeled as https://github.com/topics/xpdacq. Not sure what caused the issue. It seems you have at least one commit which went through.

**Comment by mrakitin** [comment]
I'll review your another PR #5.

**Comment by mrakitin** [comment]
@st3107, sorry, I configured the protected branches too strictly. Now it should be good. Please try to push to this branch again to test if it works fine. I can then add my review and merge. Thanks for understanding.

If it works, #5 can be closed without merging.

**Review by mrakitin — APPROVED** [review]

**Pull request merged**
